### ISSUE TITLE
Update version available via NPM

### ISSUE THREAD

**Issue by mal** [coryallegory/hubot-cah#1]
The version published on NPM crashes hubot on start up :disappointed: 

```
WARNING Expected /home/mal/code/idio/jeff/node_modules/hubot-cah/src/cards to assign a function to module.exports, got object
```

Good news is that it looks like this was fixed in the most recent commit, any chance you could publish the updated version?

Cheers!

**Comment by coryallegory** [comment]
Everything should be fixed up via npm, latest version is now 0.1.0

The README is out of date, I will get to it later when I have the chance, but you should be able to figure things out using 'hubot cah help'.
